---
language: node_js
arch:
  - amd64
  - ppc64le
before_install: npm config set ca ''
env:
  global:
  - BUSTER_TEST_OPT='--reporter specification'
  - SAUCE_USERNAME=cujojs-rest
  - SAUCE_ACCESS_KEY='083602fa-1a26-4c55-af2a-9d64a27f546e'
  - PORT=8000
cache:
  directories:
  - node_modules
sudo: false
matrix:
  include:
    - node_js: '0.10'
      script: 'travis_retry npm run-script lint'
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script buster'
      arch: amd64
    - node_js: '4'
      script: 'travis_retry npm run-script buster'
      arch: amd64
    - node_js: '6'
      script: 'travis_retry npm run-script buster'
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/chrome.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/firefox.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/firefox-45.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/firefox-38.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/edge.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/edge.json
      arch: amd64
    - node_js: '0.10'
      script: 'npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/ie-11.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/safari-9.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/safari-9.json
      arch: amd64
    - node_js: '0.10'
      script: 'npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/safari-8.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/ios-9.2.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/ios-9.2.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/ios-8.4.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/android-5.1.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/android-4.4.json
      arch: amd64
    - node_js: '0.10'
      script: 'travis_retry npm run-script sauceme'
      env:
        - BROWSERS=test/browsers/android-4.3.json
      arch: amd64
   
   
    - node_js: '4'
      script: 'travis_retry npm run-script buster'
      arch: ppc64le
    - node_js: '6'
      script: 'travis_retry npm run-script buster'
      arch: ppc64le
